### ISSUE TITLE
Settings to compute depth descriptors

### ISSUE THREAD

**Issue by rahulagrawal048** [oravus/seq2single#1]
I am trying to compute the depth descriptors using Undemon for the subset of oxford dataset provided and have the following questions:

1) What image resolution was used to predict the disparity?
2) Can you provide the algorithm and values of focal length, baseline, and image width used to compute depth from the predicted disparity?

**Comment by oravus** [comment]
Hi @rahulagrawal048,

> 1. What image resolution was used to predict the disparity?

`h, w = 256, 512`

> 2. Can you provide the algorithm and values of focal length, baseline, and image width used to compute depth from the predicted disparity?

`depth = (b * f) / (w * d)`
where, `baseline (b) = 0.5335` and `focal length (f) = 594.884637681` are the values based on the training dataset KITTI and  `width as the scaling factor (w) = 512` is used to rescale `predicted disparity (d) \in [0,1] to [0,w]`.

Hope that helps.
